



include $(THEOS)/makefiles/common.mk

TWEAK_NAME = skflyrevealloader
$(TWEAK_NAME)_FILES = Reveal2Loader.m


#skfly add begin
include $(SKFLY_COMMON_SUPPORT_PATH)/PublicMakeFile.mk
#skfly add end

include $(THEOS_MAKE_PATH)/tweak.mk


